import { STYLES } from "./config.jsx";

export const slidesContent = [
  {
    "id": "satcat-all",
    "chapter": 0,
    "step": 0,
    "data": "/data/satcat.csv",
    "type": "waffle",
    "styles": STYLES,
    "text": "Since Sputnik I, humanity has sent 63,108 satellites to space.",
  },
  {
    "id": "satcat-decayed",
    "chapter": 0,
    "step": 1,
    "data": "/data/satcat.csv",
    "filter": "decayed",
    "type": "waffle",
    "styles": STYLES,
    "text":
      "A lot of them have either returned back to Earth (sometimes injuring people) or have dissolved into Earth's lower atmosphere.",
  },
  {
    "id": "satcat-active",
    "chapter": 0,
    "step": 2,
    "data": "/data/satcat.csv",
    "filter": "decayed",
    "type": "timeline",
    "styles": STYLES,
    "text": "As of April 2025, there are 30,080 satellites orbiting Earth.",
  },
  {
    "id": "satuse-all",
    "chapter": 1,
    "step": 0,
    "data": "/data/clean_sat.csv",
    "type": "timeline",
    "styles": STYLES,
    "text":
      "The Union of Concerned Scientists has documented the use of 7,562 satellites.",
  },
  {
    "id": "satuse-use",
    "chapter": 1,
    "step": 1,
    "data": "/data/clean_sat.csv",
    "type": "timeline",
    "styles": STYLES,
    "text": "To this date X,XXX have entirely or partly commercial purposes.",
  },
  {
    "id": "satuse-starlink",
    "chapter": 1,
    "step": 2,
    "data": "/data/clean_sat.csv",
    "type": "waffle",
    "numCols": 70,
    "filter": "starlink",
    "styles": STYLES,
    "text": "These are all satellites Starlink has sent to space",
  },
  {
    "id": "space-rides-all",
    "chapter": 2,
    "step": 0,
    "data": "/data/rides-clean.csv",
    "type": "waffle",
    "numCols": 40,
    "styles": STYLES,
    "text": "Hiiii. space-rides-all",
  },
  {
    "id": "space-rides-category",
    "chapter": 2,
    "step": 1,
    "data": "/data/rides-clean.csv",
    "type": "waffle",
    "numCols": 40,
    "styles": STYLES,
    "text": "Hiiii. space-rides-all",
  },
  {
    "id": "space-rides-timeline",
    "chapter": 2,
    "step": 2,
    "data": "/data/rides-clean.csv",
    "type": "timeline",
    "styles": STYLES,
    "text": "Hiiii. space-rides-all",
  },
];
