import { STYLES } from "./config.jsx";

export const slidesContent = [
  {
    "id": "satcat-all",
    "chapter": 0,
    "step": 0,
    "data": "/data/satcat.csv",
    "type": "waffle",
    "styles": STYLES,
    "text": "We have sent .",
  },
  {
    "id": "satcat-active",
    "chapter": 0,
    "step": 1,
    "data": "/data/satcat.csv",
    "type": "timeline",
    "styles": STYLES,
    "text": "Hi. satcat-active",
  },
  {
    "id": "satuse-all",
    "chapter": 1,
    "step": 0,
    "data": "/data/clean_sat.csv",
    "type": "timeline",
    "styles": STYLES,
    "text": "Hii. satuse-all",
  },
  {
    "id": "satuse-use",
    "chapter": 1,
    "step": 1,
    "data": "/data/clean_sat.csv",
    "type": "timeline",
    "styles": STYLES,
    "text": "This is how much ",
  },
  {
    "id": "space-rides-all",
    "chapter": 2,
    "step": 0,
    "data": "/data/rides-clean.csv",
    "type": "waffle",
    "numCols": 100,
    "styles": STYLES,
    "text": "Hiiii. space-rides-all",
  },
  {
    "id": "space-rides-category",
    "chapter": 2,
    "step": 1,
    "data": "/data/rides-clean.csv",
    "type": "waffle",
    "numCols": 100,
    "styles": STYLES,
    "text": "Hiiii. space-rides-all",
  },
  {
    "id": "space-rides-timeline",
    "chapter": 2,
    "step": 2,
    "data": "/data/rides-clean.csv",
    "type": "timeline",
    "styles": STYLES,
    "text": "Hiiii. space-rides-all",
  },
];
